
import_from_git(url: "git@github.com:syngenta-digital/mobile-ruby-fastlane-shared.git",
              path: "shared-fastlane/android/Syngenta_Build_Fastfile",
              version: "~> 0.0.13")
# import "shared-lane/android/Syngenta_Build_Fastfile"

# Project Specific Variables
test_name = "test"
build_type = "debug"
slack_url = "https://hooks.slack.com/services/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"

desc "Builds and tests dev version when code changes are made in bitbucket repo"
lane :integration do |options|
    syngenta_build_android_app(
    build_type: "release",
    test: false,
    test_name: test_name,
    package: true,
    bundle_task: false,
    beta_store_upload: false,
  )
slack_notification(message: "UIKit build generation done")
end

desc "builds, creates prod facing apk, pushes to google play store alpha"
lane :delivery do |options|
    syngenta_build_android_app(
    build_type: "release",
    test: false,
    test_name: test_name,
    package: true,
    beta_store_upload: true,
    json_key: json_key,
    package_name: package_name
  )
  slack_notification(message: "Android release process done")
end

private_lane :slack_notification do |options|
  slack(
    message: options[:message],
    slack_url: slack_url,
    payload: {
      "Build Date" => Time.new.to_s
    }
  )
end
